# Root-level docker-compose.yml


services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "5000:5000"
    networks:
      - todo_net
    environment:
      - DB_HOST=auth-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=authdb
      - JWT_SECRET=your_secret
    depends_on:
      - auth-db

  auth-db:
    image: postgres:15
    restart: always
    ports:
      - 5432
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - todo_net
    volumes:
      - auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5




  todo-db:
    image: postgres:15
    restart: always
    ports:
      - 5432
    networks:
      - todo_net
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - todo_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    
volumes:
  auth_data:
  todo_data:
networks:
  todo_net:
    external: true
